name: Test deployment

on:
  push:
    # only non-main (and non-master) branches
    branches:
      - "**"
      - "!main"

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.8.0

      - name: Install dependencies
        run: just install --frozen-lockfile
      - name: Test build website
        run: just build
