name: Test build

on:
  push:
    # only non-main (and non-master) branches
    branches:
      # Getting too many 502s from the Notion API
      - disabled
      # - "**"
      # - "!main"

jobs:
  test-deploy:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v1
        with:
          just-version: '1.25.2'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.44.0"
      
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
      
      - uses: pnpm/action-setup@v4
        with:
          version: "8.15.5"

      - name: Install dependencies
        run: just _install --frozen-lockfile
      
      - name: Test build website
        run: just build
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DOCUMENT_ROOT: ${{ secrets.NOTION_DOCUMENT_ROOT }}
          NOTION_BLOG_ROOT: ${{ secrets.NOTION_BLOG_ROOT }}
